services:
  - type: web
    name: signease-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: signeaseDB
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        sync: false
      - key: ADMIN_EMAIL
        value: admin@signease.com
      - key: ADMIN_PASSWORD
        sync: false
